-- MySQL Script generated by MySQL Workbench
-- Sun May  7 10:15:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appweb_bbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appweb_bbdd
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS appweb_bbdd DEFAULT CHARACTER SET utf8 ;
USE appweb_bbdd ;

-- -----------------------------------------------------
-- TABLA: ROLES
-- -----------------------------------------------------
CREATE TABLE ROLES (
  id_rol INT NOT NULL,
  nombre_rol VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_rol)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bbdd`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE USUARIOS (
  id_rol INT NOT NULL,
  id_usuario VARCHAR(50) NOT NULL,
  nombres_usuario VARCHAR(100) NOT NULL,
  apellidos_usuario VARCHAR(100) NOT NULL,
  correo_usuario VARCHAR(100) NOT NULL,
  password_usuario VARCHAR(10) NOT NULL,
  PRIMARY KEY (id_usuario),
  UNIQUE INDEX correo_usuario_UNIQUE (correo_usuario),
  INDEX ind_usuario_rol (id_rol),
  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (id_rol)
    REFERENCES appweb_bbdd.ROLES (id_rol)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- TABLA CLIENTES
-- -----------------------------------------------------
CREATE TABLE CLIENTES (
  id_cliente VARCHAR(50) NOT NULL,
  direccion_cliente VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_cliente),
  INDEX ind_cliente_usuario (id_cliente ASC) ,
  CONSTRAINT fk_cliente_usuario
    FOREIGN KEY (id_cliente)
    REFERENCES appweb_bbdd.USUARIOS (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bbdd`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE PEDIDO (
  id_cliente VARCHAR(50) NOT NULL,
  id_pedido VARCHAR(10) NOT NULL,
  fecha_pedido DATE NOT NULL,
  PRIMARY KEY (id_pedido),
  INDEX ind_pedido_cliente (id_cliente ASC),
  CONSTRAINT fk_pedido_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES appweb_bbdd.CLIENTES (id_cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bbdd`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE CATEGORIAS (
  id_categoria INT NOT NULL,
  nombre_categoria VARCHAR(200) NOT NULL,
  PRIMARY KEY (id_categoria))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bbdd`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE PRODUCTOS (
  id_categoria INT NOT NULL,
  id_producto VARCHAR(50) NOT NULL,
  nombre_producto VARCHAR(150) NOT NULL,
  PRIMARY KEY (id_producto),
  INDEX ind_producto_categoria (id_categoria ASC),
  CONSTRAINT fk_producto_categoria
    FOREIGN KEY (id_categoria)
    REFERENCES appweb_bbdd.CATEGORIAS (id_categoria)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bbdd`.`LISTA_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE LISTA_PRODUCTOS (
  id_pedido VARCHAR(10) NOT NULL,
  id_producto VARCHAR(50) NOT NULL,
  cantidad_producto INT NOT NULL,
  INDEX ind_lista_productos_pedido (id_pedido ASC),
  INDEX ind_lista_productos_producto (id_producto ASC),
  CONSTRAINT fk_lista_productos_pedido
    FOREIGN KEY (id_pedido)
    REFERENCES appweb_bbdd.PEDIDO (id_pedido)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_lista_productos_producto
    FOREIGN KEY (id_producto)
    REFERENCES appweb_bbdd.PRODUCTOS (id_producto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
