-- MySQL Script generated by MySQL Workbench
-- Sun May 28 07:42:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema market_system_oscar_3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market_system_oscar_3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market_system_oscar_3` DEFAULT CHARACTER SET utf8 ;
USE `market_system_oscar_3` ;

-- -----------------------------------------------------
-- Table `market_system_oscar_3`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market_system_oscar_3`.`usuarios` (
  `idusuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` INT(11) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `market_system_oscar_3`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market_system_oscar_3`.`propietario` (
  `idpropietario` INT(11) NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(50) NOT NULL,
  `idusuarios` INT(11) NOT NULL,
  PRIMARY KEY (`idpropietario`),
  INDEX `fk_propietario_usuarios1_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_propietario_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `market_system_oscar_3`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
