version: '3.1'

services:
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: market_system_pro
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - 3305:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}