version: '3.1'

services:
#   db:
#     image: mysql:8.2
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_DATABASE: marketsystem
#       MYSQL_ROOT_PASSWORD: Bmptl1mT4vZMZm51ghESroxxsOX
#     ports:
#       - 3306:3306
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data: {}

  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
  
volumes:
  postgresDB:

      